### ISSUE TITLE
Toolflow setup: python version problem

### ISSUE THREAD

**Issue by KajWiik** [casper-astro/tutorials_devel#59]
In vanilla Ubuntu 20.04 installation, `/usr/bin/python` points to python v. 2.7 leading to an error during Matlab startup:
```
Warning: Executing startup failed in matlabrc.
This indicates a potentially serious problem in your MATLAB setup, which should be resolved as soon as
possible.  Error detected was:
MATLAB:undefinedVarOrClass
Undefined variable "py" or class "py.sys.path".
```
so virtualenv must be used:
```
sudo apt install python3.8-venv
cd </path/to>/sandbox
python3 -m venv casper-venv
source casper-venv/bin/activate
cd mlib_devel
pip install -r requirements.txt
```
Also add to `startsg.local`:
```
# Activate a python3 virtual-environment on load
export CASPER_PYTHON_VENV_ON_START=</path/to>/sandbox/casper-venv
```

**Comment by jack-h** [comment]
This could certainly be added _somewhere_ to the docs. Do you have a suggestion for where this should be? (The basic install docs already suggest a py3 venv for all but ancient platforms -- https://casper-toolflow.readthedocs.io/en/latest/src/Installing-the-Toolflow.html)

**Comment by jkocz** [comment]
Closing this issue, as the Readme instructions include a py3 venv creation.
