### ISSUE TITLE
Broken links in RFSoC tutorials

### ISSUE THREAD

**Issue by jkocz** [casper-astro/tutorials_devel#76]
The links from the RFSoC regarding clocking setup/config do not seem to work.

Before proceeding briefly review the clocking information for your target platform and any additional setup/configuration required:

    [ZCU216](https://casper-toolflow.readthedocs.io/projects/tutorials/en/latest/tutorials/rfsoc/platforms/zcu216.md#rf-clocking)
    [ZCU208](https://casper-toolflow.readthedocs.io/projects/tutorials/en/latest/tutorials/rfsoc/platforms/zcu208.md#rf-clocking)
    [ZCU111](https://casper-toolflow.readthedocs.io/projects/tutorials/en/latest/tutorials/rfsoc/platforms/zcu111.md#rf-clocking)
    [RFSoC2x2](https://casper-toolflow.readthedocs.io/projects/tutorials/en/latest/tutorials/rfsoc/platforms/rfsoc2x2.md#rf-clocking)
    [RFSoC4x2](https://casper-toolflow.readthedocs.io/projects/tutorials/en/latest/tutorials/rfsoc/platforms/rfsoc4x2.md#rf-clocking)
    [ZRF16](https://casper-toolflow.readthedocs.io/projects/tutorials/en/latest/tutorials/rfsoc/platforms/zrf16.md#rf-clocking)

**Comment by mitchburnett** [comment]
which file is this in?

**Comment by jkocz** [comment]
Fixed by @mitchburnett.
