### ISSUE TITLE
ValueError: Verification of write to '' at offset 0 failed. 

### ISSUE THREAD

**Issue by ywj0225** [casper-astro/tutorials_devel#83]
I followed the red_pitaya tutorial one until executing the command "fpga.write_int('a',10)" and the problem started to appear.
![Uploading NF%P2A6H{BH@QS(63P{9W2T.png…]()

**Comment by jack-h** [comment]
Thanks for raising this -- what version of `mlib_devel` were you using?
Could you provide a git hash, please?

**Comment by ywj0225** [comment]
@jack-h Hi，the version of 'mlib_devel' is m2021a. All other software is compatible（like matlabR2021a, vivado2021, ubuntu20.04). I'm sorry that I'm new to github so I don't know the git hash.  I just follow the step of website"https://casper-toolflow.readthedocs.io/projects/tutorials/en/latest/tutorials/redpitaya/tut_intro.html".  I connected the red_pitaya and uploaded my fpg.file.  But something wrong when I executed command "fpga.write_int('a',10)“.

**Comment by ywj0225** [comment]
@jack-h Hi, git hash maybe this one: 43f2d6cd994dfc684cd1e5e1c3ce85bab91e8e44

**Comment by jkocz** [comment]
Closing this as it was addressed as part of: https://github.com/casper-astro/mlib_devel/issues/208 

Fixed by downgrading to 1.04x versions of the Red Pitaya OS. 

Instructions should be added to the RP configuration to specify this (of the CASPER code recompiled to work with v2.x)
